env:
  global:
    - MAKEJOBS=-j3
    - RUN_UNIT_TESTS=true
    - RUN_FUNCTIONAL_TESTS=true
    - RUN_FUZZ_TESTS=false
    - CCACHE_MAXSIZE=100M
    - CCACHE_COMPRESS=1
jobs:
  - name: 'ARM'
    env: >-
      HOST=arm-linux-gnueabihf
      PACKAGES="python3 g++-arm-linux-gnueabihf"
      RUN_UNIT_TESTS=false
      RUN_FUNCTIONAL_TESTS=false
      GOAL="install"
      # -Wno-psabi is to disable ABI warnings: "note: parameter passing for argument of type ... changed in GCC 7.1"
      # This could be removed once the ABI change warning does not show up by default
      BITCOIN_CONFIG="--enable-glibc-back-compat --enable-reduce-exports CXXFLAGS=-Wno-psabi"
  - name: 'Win64'
    env: >-
      HOST=x86_64-w64-mingw32
      PACKAGES="python3 nsis g++-mingw-w64-x86-64 wine-binfmt wine64"
      RUN_FUNCTIONAL_TESTS=false
      GOAL="deploy"
      BITCOIN_CONFIG="--enable-reduce-exports --disable-gui-tests"
  - name: 'Linux x86_64'
    env: >-
      HOST=x86_64-unknown-linux-gnu
      PACKAGES="python3-zmq xorg"
      GOAL="install"
      BITCOIN_CONFIG="--enable-glibc-back-compat --enable-reduce-exports"
  - name: 'Linux32'
    env: >-
      ADDARCH=i386
      HOST=i686-pc-linux-gnu
      PACKAGES="g++-multilib python3-zmq libfontconfig1:i386 libxcb1:i386"
      GOAL="install"
      BITCOIN_CONFIG="--enable-zmq --with-gui=qt5 --disable-bip70 --enable-glibc-back-compat --enable-reduce-exports LDFLAGS=-static-libstdc++"
  - name: 'macOS'
    env: >-
      HOST=x86_64-apple-darwin14
      PACKAGES="cmake imagemagick libcap-dev librsvg2-bin libz-dev libbz2-dev libtiff-tools python3-dev python3-setuptools"
      GOAL="deploy"
      RUN_UNIT_TESTS=false
      RUN_FUNCTIONAL_TESTS=false
      OSX_SDK="10.11"
      BITCOIN_CONFIG="--enable-gui --enable-reduce-exports --enable-werror"
